ec.refocus sets window topmost (#447)
Co-authored-by: Eric Larson <larson.eric.d@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,30 +2,46 @@ version: 2
 jobs:
   build_docs:
     docker:
-      - image: circleci/python:3.8.5-buster
+      - image: cimg/base:current-22.04
     steps:
       # Get our data and merge with upstream
       - checkout
-      - run: echo $(git log -1 --pretty=%B) | tee gitlog.txt
-      - run: echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
-      - run: sudo apt update
-      - run: sudo apt install libglu1-mesa ffmpeg
       - run:
-         command: |
-           if [[ $(cat merge.txt) != "" ]]; then
-             echo "Merging $(cat merge.txt)";
-             git pull --ff-only origin "refs/pull/$(cat merge.txt)/merge";
-           fi
-      - run: echo "export DISPLAY=:99" >> $BASH_ENV
-      - run: echo "export _EXPYFUN_SILENT=true" >> $BASH_ENV
-      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
-      - run: echo "export SOUND_CARD_BACKEND=pyglet >> $BASH_ENV"  # rtmixer needs pulse, which is a huge pain to get running on CircleCI
-      - run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
-      - run: pip install --quiet --upgrade --user pip
-      - run: pip install --quiet --upgrade --user numpy scipy matplotlib sphinx pillow pandas h5py mne pyglet psutil sphinx_bootstrap_theme sphinx_fontawesome numpydoc https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master
+          name: Merge
+          command: |
+            set -eo pipefail
+            echo $(git log -1 --pretty=%B) | tee gitlog.txt
+            echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
+            if [[ $(cat merge.txt) != "" ]]; then
+              echo "Merging $(cat merge.txt)";
+              git pull --ff-only origin "refs/pull/$(cat merge.txt)/merge";
+            fi
+      - run:
+          name: Prep env
+          command: |
+            set -eo pipefail
+            echo "set -eo pipefail" >> $BASH_ENV
+            sudo apt update
+            sudo apt install libglu1-mesa python3.10-venv python3-venv libxft2 ffmpeg ffmpeg xvfb
+            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
+            python3.10 -m venv ~/python_env
+            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
+            echo "export SOUND_CARD_BACKEND=pyglet >> $BASH_ENV"  # rtmixer needs pulse, which is a huge pain to get running on CircleCI
+            echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
+            echo "export XDG_RUNTIME_DIR=/tmp/runtime-circleci" >> $BASH_ENV
+            echo "export PATH=~/.local/bin/:$PATH" >> $BASH_ENV
+            echo "export DISPLAY=:99" >> $BASH_ENV
+            echo "export _EXPYFUN_SILENT=true" >> $BASH_ENV
+            echo "source ~/python_env/bin/activate" >> $BASH_ENV
+            mkdir -p ~/.local/bin
+            ln -s ~/python_env/bin/python ~/.local/bin/python
+            echo "BASH_ENV:"
+            cat $BASH_ENV
+      - run: pip install --quiet --upgrade pip setuptools wheel
+      - run: pip install --quiet --upgrade numpy scipy matplotlib sphinx pillow pandas h5py mne "pyglet<2.0" psutil sphinx_bootstrap_theme sphinx_fontawesome numpydoc https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master
       - run: python -c "import mne; mne.sys_info()"
       - run: python -c "import pyglet; print(pyglet.version)"
-      - run: python setup.py develop --user
+      - run: python setup.py develop
       - run: cd doc && make html
 
       - store_artifacts:
